[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor Baudrate
monitor_speed = 115200

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBUILD_TIMESTAMP=$UNIX_TIME

; Library dependencies
lib_deps =
    fastled/FastLED@^3.6.0
    bblanchon/ArduinoJson@^6.21.3
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    knolleary/PubSubClient@^2.8

; File system
board_build.filesystem = littlefs

; Upload speed
upload_speed = 921600

; OTA (Over-The-Air) Upload Configuration
upload_protocol = espota
upload_port = 192.168.3.71
upload_flags =
    --auth=hexlight-ota-2024
